build:
  script: cd BranchMerge && make tests
  stage: build
  tags:
    - CSC340
  artifacts:
    paths:
      [BranchMerge/tests]

test:
  script: BranchMerge/tests
  stage: test
  tags:
    - CSC340
  needs: [build]
