build:
  script: cd BranchMerge && make tests && cd .. && cd UnitTests && make tests
  stage: build
  tags:
    - csc340
  artifacts:
    paths:
      [BranchMerge/tests]
	  [UnitTests/tests]

test:
  script: BranchMerge/tests/../UnitTests/Tests
  stage: test
  tags:
    - csc340
  needs: [build]
