job 1:
    tags: CSC340
    stage: build
    script: cd UnitTests && make tests
    artifacts:
        paths:
            [UnitTests/tests]

job 2:
    tags: CSC340
    stage: test
    needs: [build]
    script: UnitTests/tests
